# -*- coding: utf-8 -*-
"""词库扩展阶段二:词根表扩充(272 → 500+)。
每个新根/新前缀给出含义;例词由拆词器在库内自动验证,少于 3 例的自动剔除并记日志
(见 build_data.py 的 stage2 报告)——满足规格 §6「含义 + ≥3 个库内例词」。
"""

# 新增词根(key, surfaces, meaning)
NEW_ROOTS = [
    ("aer", ["aer", "aero"], "空气"),
    ("am", ["amat", "amor", "ami"], "爱"),
    ("ampl", ["ampl", "ampli"], "大;扩大"),
    ("anim", ["anim"], "心神;生命"),
    ("anthrop", ["anthrop", "anthropo"], "人类"),
    ("arbitr", ["arbitr"], "评判"),
    ("artic", ["artic"], "关节;接合"),
    ("auth", ["auth"], "创始;权威"),
    ("calcul", ["calcul"], "石子;计算"),
    ("carn", ["carn"], "肉"),
    ("cardi", ["cardi", "cardin"], "心"),
    ("cav", ["cav", "cavern"], "洞;挖"),
    ("chrom", ["chrom", "chromo"], "颜色"),
    ("chron", ["chron"], "时间"),
    ("cruis", ["cruis", "crui"], "巡航"),
    ("cub", ["cub"], "躺"),
    ("custom", ["custom"], "习惯"),
    ("derm", ["derm", "dermat"], "皮肤"),
    ("ego", ["ego"], "自我"),
    ("erg", ["erg", "ergo"], "功;能量"),
    ("examin", ["examin", "exam"], "检查"),
    ("femin", ["femin", "feminin"], "女人"),
    ("ferv", ["ferv"], "沸;热"),
    ("forest", ["forest"], "森林"),
    ("fug", ["fug", "fugit"], "逃;离开"),
    ("glor", ["glor"], "光荣"),
    ("gran", ["gran", "grain"], "谷粒;颗粒"),
    ("hal", ["hal"], "呼吸"),
    ("herb", ["herb"], "草"),
    ("hydr", ["hydr"], "水"),
    ("imper", ["emper", "imper", "imperi"], "帝国;统治"),
    ("insul", ["insul", "insulo"], "岛"),
    ("later", ["later", "latera"], "边"),
    ("lingu", ["lingu"], "语言"),
    ("luc", ["luc", "lucr"], "光"),
    ("lumin", ["lumin"], "光;照明"),
    ("lun", ["lun"], "月亮"),
    ("matr", ["matr", "matern"], "母亲"),
    ("morph", ["morph", "morpho"], "形"),
    ("mort", ["mort"], "死"),
    ("mount", ["mount", "mont"], "山;登上"),
    ("neur", ["neur", "neuro"], "神经"),
    ("onym", ["onym", "onyma"], "名"),
    ("pass", ["pass", "passi"], "通过"),
    ("plac", ["plac", "placat"], "抚慰;平静"),
    ("publ", ["publ", "publish"], "公众"),
    ("rog", ["rog", "roga"], "问;要求"),
    ("rot", ["rot", "rota"], "轮;转"),
    ("salv", ["salv"], "拯救"),
    ("semin", ["semin"], "种子"),
    ("skep", ["skep", "skept"], "怀疑"),
    ("spac", ["spac", "spacio"], "空间"),
    ("speci", ["speci"], "种类;特别"),
    ("stell", ["stell", "stella"], "星"),
    ("strat", ["strat"], "层"),
    ("stup", ["stup"], "迷惑"),
    ("tenu", ["tenu"], "薄;细"),
    ("tox", ["tox", "toxic"], "毒"),
    ("triv", ["triv"], "三;路岔"),
    ("tut", ["tut", "tuit"], "看护;教"),
    ("veng", ["veng", "vengi"], "报仇"),
    ("verg", ["verg", "verge"], "转向"),
    ("vibr", ["vibr"], "摇动"),
    ("vind", ["vind", "vindic"], "辩护;复仇"),
    ("zon", ["zon"], "带"),
    ("line", ["line"], "线"),
    ("mechan", ["mechan", "mechi"], "机器"),
    ("ponder", ["ponder", "pond"], "权衡"),
    ("chem", ["chem", "chemi"], "化学"),
    ("journ", ["journ", "journi"], "日"),
    ("congru", ["congru"], "一致"),
    ("person", ["person"], "人"),
    ("radi", ["radi", "radio"], "射线;根"),
    ("plant", ["plant", "planta"], "种植"),
    ("date", ["date"], "日期"),
    ("range", ["range", "rang"], "排列;秩"),
    ("character", ["character", "characteri"], "刻;特征"),
    ("devi", ["devi"], "偏路"),
    ("sight", ["sight"], "看见"),
    ("fresh", ["fresh"], "新鲜"),
    ("fruit", ["fruit", "fruct"], "果实"),
    ("industr", ["industr"], "勤勉"),
    ("modern", ["modern"], "现代"),
    ("moment", ["moment", "momenti"], "时刻"),
    ("satisfact", ["satisfact"], "满足"),
    ("prec", ["prec"], "恳求;切断"),
    ("trench", ["trench"], "切;挖"),
    ("abol", ["abol"], "消灭"),
    ("argu", ["argu"], "争论"),
    ("balance", ["balance", "balan"], "天平;平衡"),
    ("come", ["come"], "来"),
    ("charge", ["charge", "charg"], "装载;收费"),
    ("change", ["change", "chang"], "交换;变"),
    ("child", ["child"], "孩子"),
    ("doubt", ["doubt"], "怀疑"),
    ("load", ["load"], "装载"),
    ("govern", ["govern", "governi"], "领航;统治"),
    ("harm", ["harm"], "伤害"),
    ("take", ["take"], "拿"),
    ("cast", ["cast"], "投"),
    ("still", ["still"], "滴;静"),
    ("past", ["past"], "放牧;过"),
    ("rest", ["rest"], "停留;剩余"),
    ("member", ["member", "memberi"], "成员"),
    ("legislat", ["legislat"], "立法"),
    ("maxim", ["maxim", "maxima"], "最大"),
    ("necess", ["necess"], "必需"),
    ("symbol", ["symbol"], "象征"),
    ("warr", ["warr", "war"], "担保;保护"),
    ("join", ["join", "joint"], "连接"),
    ("sort", ["sort", "sorti"], "种类;伴"),
    ("cili", ["cili"], "睫毛;招引"),
    ("cant", ["cant", "cent"], "唱"),
    ("nomin", ["nomin", "nomen"], "名"),
    ("empt", ["empt"], "买;取"),
    ("hilar", ["hilar"], "欢"),
    ("expedi", ["expedi"], "使成;便利"),
    ("tric", ["tric"], "纠缠"),
    ("fall", ["fall", "fals"], "欺;错"),
    ("fatu", ["fatu"], "愚"),
    ("prud", ["prud"], "谨慎"),
    ("timid", ["timid"], "怕"),
    ("rever", ["rever"], "敬畏"),
    ("lubric", ["lubric"], "滑"),
    ("medit", ["medit"], "思考"),
    ("parl", ["parl"], "说"),
    ("piti", ["piti"], "怜悯"),
    ("precipit", ["precipit"], "前头;投"),
    ("greg", ["greg"], "群"),
    ("joy", ["joy", "enjo"], "乐"),
    ("title", ["title"], "题;名"),
    ("danger", ["danger"], "危险"),
    ("decor", ["decor"], "装饰;礼"),
    ("light", ["light"], "光"),
    ("element", ["element"], "元素"),
    ("gust", ["gust"], "尝"),
    ("fabric", ["fabric"], "工坊;织物"),
    ("faith", ["faith"], "信"),
    ("fault", ["fault"], "欺;过"),
    ("grace", ["grace"], "雅;恩"),
    ("hist", ["hist"], "历史"),
    ("immun", ["immun"], "免疫"),
    ("magic", ["magic"], "魔"),
    ("miser", ["miser"], "怜;惨"),
    ("music", ["music"], "乐"),
    ("night", ["night"], "夜"),
    ("obedi", ["obedi"], "服从"),
    ("odor", ["odor", "odour"], "气味"),
    ("peril", ["peril"], "危险"),
    ("pessim", ["pessim"], "最坏;悲观"),
    ("planet", ["planet", "planeta"], "行星"),
    ("polar", ["polar"], "极"),
    ("new", ["new"], "新"),
    ("deter", ["deter"], "吓住"),
    ("flict", ["flict"], "打击"),
    ("tail", ["tail", "tailo"], "裁;尾"),
    ("like", ["like"], "相像"),
    ("haust", ["haust"], "抽;拉"),
    ("favor", ["favor", "fav", "favour", "favoura"], "恩宠"),
    ("patr", ["patr", "patro"], "父;祖国"),
    ("cycle", ["cycl", "cycle"], "圆环;轮"),
    ("laps", ["laps", "lapse"], "滑;落"),
    ("plain", ["plain"], "平;诉"),
    ("environ", ["environ"], "包围;环境"),
    ("tangle", ["tangle", "tangl"], "缠"),
    ("figure", ["fig", "figur"], "塑;形"),
    ("twine", ["twine", "twin"], "缠"),
    ("vast", ["vast"], "荒;巨"),
    ("abort", ["abort"], "流产"),
    ("sciss", ["sciss", "scis"], "剪"),
]

# 新增前缀(key, surfaces, meaning)
NEW_PREFIXES = [
    ("hydro", ["hydro"], "水"),
    ("mal", ["mal"], "坏;错误"),
    ("omni", ["omni"], "全;都"),
    ("peri", ["peri"], "周围"),
    ("phil", ["phil", "philo"], "爱"),
    ("mono", ["mono"], "单一;独"),
]

# 既有根的词面扩充(补拆词缺口,如 disaster=dis+aster、invention=in+vent)
SURFACE_EXT = {
    "astr": ["aster"],
    "ven": ["vent", "veni"],
    "spect": ["spec", "spic"],
    "tain": ["tinu"],
    "cur": ["curr", "curs"],
    "grad": ["gress", "gradu"],
    "vid": ["view"],
    "pel": ["pulse"],
    "pend": ["pond"],
    "mit": ["miss"],
    "pos": ["pone", "posit"],
    "press": ["print"],
    "struct": ["strue", "stru"],
    "tract": ["treat", "train"],
    "vert": ["verse"],
    "vol": ["volunt"],
    "frag": ["fract"],
    "flect": ["flex"],
    "sci": ["scien"],
    "cand": ["candid", "candle"],
    "capt": ["cept", "ceive", "ceiv", "cip"],
    "val": ["vail"],
    "voc": ["vok"],
    "point": ["punct"],
    "ab": ["abs"],
    "part": ["partner"],
    "tort": ["tor", "tors"],
    "pun": ["pung"],
    "ut": ["util", "utilis"],
    "civ": ["civil", "civili"],
    "sent": ["senti"],
    "act": ["activ", "activi"],
    "fam": ["famili"],
    "imag": ["imagin", "imaginat"],
    "nat": ["natur", "natura"],
    "priv": ["privat"],
    "post": ["poster"],
    "hon": ["honour", "honor"],
    "tir": ["tire"],
    "loqu": ["locut"],
    "jud": ["judic"],
    "spir": ["spire"],
    "min": ["minim"],
    "fus": ["fuse"],
    "eco": ["econom", "economi"],
    "mob": ["mobil", "mobili", "mobiliz"],
    "alter": ["altern", "alternat"],
    "terr": ["ter", "deter"],
}
